import type { Metadata } from "next";
import { Arimo, Mulish, Space_Mono } from "next/font/google";
import "./globals.css";
import ConvexClientProvider from "@/components/ConvexClientProvider";
import { Toaster } from "@/components/ui/sonner";
import BottomNav from "@/components/BottomNav";
import Header from "@/components/Header";

const arimo = Arimo({
  variable: "--font-arimo",
  subsets: ["latin"],
});

const mulish = Mulish({
  variable: "--font-mulish",
  subsets: ["latin"],
});

const spaceMono = Space_Mono({
  variable: "--font-space-mono",
  subsets: ["latin"],
  weight: ["400", "700"], 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/convex.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${arimo.variable} ${mulish.variable} ${spaceMono.variable} antialiased`}
      >
        <Toaster
  position="top-center"
/>
<div className="lg:hidden">
<Header />
        <div className="p-4">
        <ConvexClientProvider>{children}</ConvexClientProvider>
        </div>
        

        <BottomNav />
        </div>

        <div className="hidden lg:flex items-center justify-center p-6 bg-gradient-to-r from-blue-50 to-blue-100 border border-blue-200 rounded-lg shadow-sm ">
  <p className="text-blue-700 font-medium">
    Visit the site on a phone or tablet
  </p>
</div>
      </body>
    </html>
  );
}
